---
bundle_root: null
ckpt_path: "$@bundle_root + '/model_fold' + str(@fold)"
data_file_base_dir: null
data_list_file_path: null
fold: 0

transforms:
  resample_to_spacing: "$@training#resample_to_spacing"

cache_rate: 1
train_cache_rate: "$@cache_rate"
validate_cache_rate: "$@cache_rate"

training:
  # hyper-parameters
  amp: true
  determ: false
  input_channels: null
  learning_rate: 0.2
  num_images_per_batch: 2
  num_epochs: 2000
  num_epochs_per_validation: 20
  num_patches_per_image: 1
  num_sw_batch_size: 2
  num_workers: 8
  num_cache_workers: 8
  output_classes: null
  overlap_ratio: 0.625
  patch_size: null
  patch_size_valid: null
  resample_to_spacing: null
  sw_input_on_cpu: false
  softmax: true

  loss:
    _target_: DiceFocalLoss
    include_background: true
    to_onehot_y: "$@training#softmax"
    softmax: "$@training#softmax"
    sigmoid: "$not @training#softmax"
    squared_pred: true
    batch: true
    smooth_nr: 1.0e-05
    smooth_dr: 1.0e-05
  optimizer:
    _target_: torch.optim.SGD
    lr: "@training#learning_rate"
    momentum: 0.9
    weight_decay: 4.0e-05
  lr_scheduler:
    _target_: torch.optim.lr_scheduler.PolynomialLR
    optimizer: "$@training#optimizer"
    power: 0.5
    total_iters: '$@training#num_epochs // @training#num_epochs_per_validation + 1'

# fine-tuning
finetune:
  activate: false
  pretrained_ckpt_name: "$@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt'"

# validation
validate:
  ckpt_name: "$@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt'"
  save_mask: true
  output_path: "$@bundle_root + '/prediction_fold' + str(@fold)"

# inference
infer:
  ckpt_name: "$@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt'"
  fast: false
  data_list_key: testing
  output_path: "$@bundle_root + '/prediction_' + @infer#data_list_key"
