image_key: image
label_key: label
transforms_validate:
  _target_: Compose
  transforms:
  - _target_: LoadImaged
    keys:
    - '@image_key'
    - '@label_key'
  - _target_: EnsureChannelFirstd
    keys:
    - '@image_key'
    - '@label_key'
  - _target_: Orientationd
    axcodes: RAS
    keys:
    - '@image_key'
    - '@label_key'
  - _target_: Spacingd
    align_corners:
    - true
    - true
    keys:
    - '@image_key'
    - '@label_key'
    mode:
    - bilinear
    - nearest
    pixdim: "$@resample_to_spacing"
  - _target_: CastToTyped
    keys: "@image_key"
    dtype: "$torch.float32"
  - PLACEHOLDER_INTENSITY_NORMALIZATION
  - _target_: CastToTyped
    dtype:
    - $torch.float32
    - $torch.uint8
    keys:
    - '@image_key'
    - '@label_key'
